permissions:
  contents: read

jobs:
  lint:
    env:
      FORCE_COLOR: '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: ./.github/actions/prepare
      - run: npm run lint

name: Lint

on: [push, pull_request]
